//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parlem.Customers.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int customerId { get; set; }
        public string docType { get; set; }
        public string docNum { get; set; }
        public string email { get; set; }
        public string givenName { get; set; }
        public string familyName { get; set; }
        public Nullable<int> phone { get; set; }
    }
}
