//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parlem.Customers.DataBase.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int serviceId { get; set; }
        public string productName { get; set; }
        public string productNameType { get; set; }
        public Nullable<int> numeracioTerminal { get; set; }
        public Nullable<System.DateTime> soldAt { get; set; }
        public Nullable<int> customerId { get; set; }
    }
}
